using UnityEngine;

public class escudopeque침o : MonoBehaviour
{
    public GameObject escudo; // Asigna el objeto que quieres instanciar en el Inspector
    public Transform firePoint; // Asigna el objeto "fire point" en el Inspector
    public float distanciaDeAparicion = 2f;

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.P))
        {
            SpawnObject();
        }
    }

    void SpawnObject()
    {
        // Calcula la posici칩n de aparici칩n a una cierta distancia desde el "fire point"
        Vector3 posicionDeAparicion = firePoint.position + firePoint.forward * distanciaDeAparicion;

        // Instancia el objeto en la posici칩n calculada
        Instantiate(escudo, posicionDeAparicion, Quaternion.identity);
    }
}
